### ISSUE TITLE
Errors when trying to download sound data

### ISSUE THREAD

**Issue by jfy133** [mribeirodantas/nf-whisper#6]
This is happening both locally and on gitpod with this command:

```bash
nextflow run main.nf --youtube_url 'https://www.youtube.com/watch?v=ZHlwjD08FBo&list=PL3olEEj2ioAVSCqDUCauAA_Mm6hW_JGwz' --model small.en -with-docker whisper --timstamp
```

```
ERROR ~ Error executing process > 'DOWNLOAD_AUDIO'

Caused by:
  Process `DOWNLOAD_AUDIO` terminated with an error exit status (1)

Command executed:

  #!/usr/bin/env python3
  
  import pytube # download youtube videos
  
  data = pytube.YouTube("https://www.youtube.com/watch?v=ZHlwjD08FBo&list=PL3olEEj2ioAVSCqDUCauAA_Mm6hW_JGwz")
  # Convert to audio file
  audio = data.streams.get_audio_only()
  audio.download(filename="audio.mp4")

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pytube/__main__.py", line 181, in fmt_streams
      extract.apply_signature(stream_manifest, self.vid_info, self.js)
    File "/usr/local/lib/python3.9/site-packages/pytube/extract.py", line 409, in apply_signature
      cipher = Cipher(js=js)
    File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 43, in __init__
      self.throttling_plan = get_throttling_plan(js)
    File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 405, in get_throttling_plan
      raw_code = get_throttling_function_code(js)
    File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 311, in get_throttling_function_code
      name = re.escape(get_throttling_function_name(js))
    File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 296, in get_throttling_function_name
      raise RegexMatchError(
  pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File ".command.sh", line 7, in <module>
      audio = data.streams.get_audio_only()
    File "/usr/local/lib/python3.9/site-packages/pytube/__main__.py", line 296, in streams
      return StreamQuery(self.fmt_streams)
    File "/usr/local/lib/python3.9/site-packages/pytube/__main__.py", line 188, in fmt_streams
      extract.apply_signature(stream_manifest, self.vid_info, self.js)
    File "/usr/local/lib/python3.9/site-packages/pytube/extract.py", line 409, in apply_signature
      cipher = Cipher(js=js)
    File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 43, in __init__
      self.throttling_plan = get_throttling_plan(js)
    File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 405, in get_throttling_plan
      raw_code = get_throttling_function_code(js)
    File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 311, in get_throttling_function_code
      name = re.escape(get_throttling_function_name(js))
    File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 296, in get_throttling_function_name
      raise RegexMatchError(
  pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

Work dir:
  /workspace/gitpod/work/14/e07221050043f742bbf4daf3ac759d

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
 ```

**Comment by mribeirodantas** [comment]
Sorry, James. In the current version of nf-whisper, you have to escape the URL 😅 e.g. https://www.youtube.com/watch\?v\=UVzLd304keA

**Comment by mribeirodantas** [comment]
I was able to get past this first process with `-with-wave`. Could you please try the latest version of this repo with Wave to make sure it also works for you?

**Comment by jfy133** [comment]
Awesome! OK I will try that next time I use the pipeline :D

**Comment by mribeirodantas** [comment]
The last commit fixed this. pytube still hasn't fixed this bug 🙄 but someone created a new Python package... pytubefix 😆
